# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyblogapp', '0002_auto_20160204_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
